tasks:
  hotfixes:
    command: hotfixes

  networking:
    command: networking
    requires: [hotfixes]

  run_keys:
    command: run-keys
    requires: [networking]

  services:
    command: services
    requires: [run_keys]

  software:
    command: software
    requires: [services]

  prefetch:
    command: prefetch
    requires: [software]

  usb:
    command: usb
    requires: [prefetch]

  eventlogs:
    command: eventlogs
    requires: [usb]

#  prefetch_report:
#    command: report
#    arguments:
#      filter:
#        - type: prefetch
#      template: prefetch.tmpl.j2
#    requires: [prefetch]

#  autoruns_csv:
#    command: csv
#    # arguments: runkey Name Command SID
#    arguments:
#      filter:
#        - type: file
#          name: test.foo
#        - type: registry
#    requires: [run_keys]

#  shimcache:
#    command: shimcache
