name: CI
on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  forensicworkflows:
    name: forensicworkflows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Setup go 1.13
        uses: actions/setup-go@v1
        with: {go-version: '1.13'}
      - uses: actions/setup-python@v1
        with: {python-version: '3.8'}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set system path
        run: echo "##[add-path]$(go env GOPATH)/bin"
        shell: bash
      - name: Download dependencies
        run: go mod download

      - name: Install golangci-lint & go-acc
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.1
          go get -u github.com/ory/go-acc
        shell: bash

      - name: Setup Build
        run: go generate

      - name: Lint
        run: |
          go build .
          golangci-lint run --verbose --config test/.golangci.yml
        shell: bash
      - name: Test
        run: go-acc ./...
        shell: bash
      - name: Upload coverage
        env:
          CI: "true"
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash) -f coverage.txt
        # if: matrix.os == 'windows-latest'
        shell: bash

      # - name: Setup node
      #   uses: actions/setup-node@v1
      #   with: {node-version: '10.x'}
      # - name: Install bats
      #   run: npm install -g bats

      - name: Build
        run: |
          go build .
          go install .

      - name: Move Binary
        run: |
          mkdir bin
          mv forensicworkflows* bin
        shell: bash
      # - name: Bats test
      #   run: bats test/bats/forensicworkflows.bats
      #   shell: bash
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: forensicworkflows ${{ matrix.os }}
          path: bin
